import {
  User,
  CoachProfile,
  FreeWorkout,
  FreeNutrition,
  Product,
  Conversation,
  Message,
  WeightLogEntry,
  WorkoutVolumeEntry,
  ProgressPhotoEntry,
} from '../types';

export const INITIAL_USER: User = {
  _id: 'user_athlete_01',
  email: 'athlete@smartcoach.io',
  role: 'Customer',
  firstName: 'Marcus',
  lastName: 'Vance',
  gender: 'Male',
  height: 182,
  weight: 79.5,
  targetWeight: 83.0,
  fitnessGoal: 'Gain Muscle',
  fitnessLevel: 'Intermediate',
  dietaryPreference: 'High Protein',
  allergies: [],
  dailyCalorieTarget: 2750,
  dailyWaterTarget: 3500,
  onboardingCompleted: true,
  createdAt: '2026-01-10T10:00:00.000Z',
};

export const MOCK_COACHES: CoachProfile[] = [
  {
    _id: 'coach_01',
    userId: {
      _id: 'user_coach_01',
      firstName: 'Elena',
      lastName: 'Rostova',
      email: 'elena@smartcoach.io',
      role: 'Coach',
    },
    bio: 'Olympic lifting specialist and CSCS with 9+ years coaching competitive athletes and transformation clients.',
    specialties: ['Hypertrophy', 'Olympic Lifting', 'Body Recomposition'],
    experienceYears: 9,
    certifications: ['CSCS (NSCA)', 'USAW Level 2', 'Precision Nutrition L1'],
    hourlyRate: 85,
    monthlyRate: 249,
    averageRating: 4.9,
    reviewCount: 48,
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?auto=format&fit=crop&q=80&w=400',
    clientCount: 34,
  },
  {
    _id: 'coach_02',
    userId: {
      _id: 'user_coach_02',
      firstName: 'David',
      lastName: 'Kovac',
      email: 'david@smartcoach.io',
      role: 'Coach',
    },
    bio: 'Former collegiate strength coach focusing on functional longevity, core biomechanics, and rapid fat loss.',
    specialties: ['Functional Training', 'Fat Loss', 'Mobility & Rehab'],
    experienceYears: 7,
    certifications: ['NASM-CPT', 'FMS Level 2', 'EXOS Performance Specialist'],
    hourlyRate: 75,
    monthlyRate: 219,
    averageRating: 4.8,
    reviewCount: 62,
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?auto=format&fit=crop&q=80&w=400',
    clientCount: 41,
  },
  {
    _id: 'coach_03',
    userId: {
      _id: 'user_coach_03',
      firstName: 'Aria',
      lastName: 'Chen',
      email: 'aria@smartcoach.io',
      role: 'Coach',
    },
    bio: 'Endurance coach and sports nutritionist helping athletes conquer triathlons, half-marathons, and peak energy.',
    specialties: ['Endurance', 'Sports Nutrition', 'VO2 Max Conditioning'],
    experienceYears: 6,
    certifications: ['ACSM-EP', 'ISSN Certified Sports Nutritionist', 'IRONMAN Coach'],
    hourlyRate: 80,
    monthlyRate: 235,
    averageRating: 5.0,
    reviewCount: 39,
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1548690312-e3b507d8c110?auto=format&fit=crop&q=80&w=400',
    clientCount: 29,
  },
  {
    _id: 'coach_04',
    userId: {
      _id: 'user_coach_04',
      firstName: 'Tariq',
      lastName: 'Mansour',
      email: 'tariq@smartcoach.io',
      role: 'Coach',
    },
    bio: 'Calisthenics master & strength trainer specializing in bodyweight mastery, gymnastics rings, and explosive power.',
    specialties: ['Calisthenics', 'Strength & Power', 'Kettlebells'],
    experienceYears: 8,
    certifications: ['StrongFirst SFG II', 'World Street Workout Certified'],
    hourlyRate: 70,
    monthlyRate: 199,
    averageRating: 4.9,
    reviewCount: 53,
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    clientCount: 37,
  },
];

export const MOCK_WORKOUTS: FreeWorkout[] = [
  {
    _id: 'w_01',
    title: 'Upper Body Hypertrophy Blitz',
    description: 'High-density hypertrophy session hitting chest, delts, and lats with mechanical tension and controlled eccentrics.',
    difficulty: 'Intermediate',
    category: 'Hypertrophy',
    duration: 52,
    calories: 460,
    tags: ['Chest', 'Back', 'Shoulders', 'Hypertrophy'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&q=80&w=600',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    exercises: [
      {
        id: 'e_1',
        name: 'Incline Dumbbell Bench Press',
        sets: 4,
        reps: 10,
        weight: 32,
        restSeconds: 90,
        targetMuscle: 'Upper Chest',
        instructions: ['Set bench to 30 degrees', 'Retract scapulae and lower under control (3s)', 'Drive up with explosive intent'],
      },
      {
        id: 'e_2',
        name: 'Neutral Grip Chest-Supported Row',
        sets: 4,
        reps: 12,
        weight: 40,
        restSeconds: 75,
        targetMuscle: 'Lats & Rhomboids',
        instructions: ['Lock sternum to pad', 'Pull elbows back past torso', 'Pause 1s at peak contraction'],
      },
      {
        id: 'e_3',
        name: 'Standing Cable Lateral Raises',
        sets: 4,
        reps: 15,
        weight: 12,
        restSeconds: 60,
        targetMuscle: 'Lateral Deltoids',
        instructions: ['Maintain slight elbow bend', 'Lead with elbows slightly forward', 'Resist the negative'],
      },
      {
        id: 'e_4',
        name: 'Rope Tricep Overhead Extension',
        sets: 3,
        reps: 12,
        weight: 24,
        restSeconds: 60,
        targetMuscle: 'Triceps Long Head',
        instructions: ['Flare rope wide at top lock-out', 'Deep stretch at bottom behind head'],
      },
    ],
  },
  {
    _id: 'w_02',
    title: 'Posterior Chain & Quad Annihilation',
    description: 'Heavy compound leg day emphasizing Romanian deadlifts, Bulgarian split squats, and leg extension drop sets.',
    difficulty: 'Advanced',
    category: 'Strength',
    duration: 60,
    calories: 580,
    tags: ['Quads', 'Hamstrings', 'Glutes', 'Strength'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1434682881908-b43d0467b798?auto=format&fit=crop&q=80&w=600',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    exercises: [
      {
        id: 'e_21',
        name: 'Barbell Back Squat',
        sets: 4,
        reps: 8,
        weight: 110,
        restSeconds: 120,
        targetMuscle: 'Quads & Glutes',
        instructions: ['Hit parallel depth or deeper', 'Brace core with Valsalva maneuver', 'Drive feet through floor'],
      },
      {
        id: 'e_22',
        name: 'Romanian Deadlift (Dumbbell or Barbell)',
        sets: 3,
        reps: 10,
        weight: 90,
        restSeconds: 90,
        targetMuscle: 'Hamstrings & Glutes',
        instructions: ['Hinge strictly at hips', 'Feel maximum hamstring stretch below knees', 'Neutral spine'],
      },
      {
        id: 'e_23',
        name: 'Bulgarian Split Squat',
        sets: 3,
        reps: 10,
        weight: 22,
        restSeconds: 75,
        targetMuscle: 'Quads & Stability',
        instructions: ['Rear foot elevated on bench', 'Slight forward lean to engage glutes'],
      },
      {
        id: 'e_24',
        name: 'Standing Calf Raises',
        sets: 4,
        reps: 15,
        weight: 60,
        restSeconds: 45,
        targetMuscle: 'Gastrocnemius',
        instructions: ['2s pause at bottom stretch', 'Explosive drive up onto balls of feet'],
      },
    ],
  },
  {
    _id: 'w_03',
    title: 'Metabolic HIIT & Core Ignition',
    description: 'Fast-paced athletic conditioning interval session designed to maximize calorie burn and cardiovascular engine.',
    difficulty: 'Beginner',
    category: 'HIIT',
    duration: 35,
    calories: 390,
    tags: ['Cardio', 'HIIT', 'Core', 'Fat Loss'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=600',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    exercises: [
      {
        id: 'e_31',
        name: 'Kettlebell Swings',
        sets: 4,
        reps: 20,
        weight: 20,
        restSeconds: 45,
        targetMuscle: 'Glutes & Core',
        instructions: ['Snap hips forward explosively', 'Do not squat the swing'],
      },
      {
        id: 'e_32',
        name: 'Battle Ropes Wave Intervals',
        sets: 4,
        reps: 30, // seconds
        restSeconds: 45,
        targetMuscle: 'Full Body & Delts',
        instructions: ['High-speed alternating waves with athletic athletic base stance'],
      },
      {
        id: 'e_33',
        name: 'Hanging Leg Raises',
        sets: 3,
        reps: 12,
        restSeconds: 45,
        targetMuscle: 'Abs & Hip Flexors',
        instructions: ['No swinging', 'Roll pelvis up toward ribs'],
      },
    ],
  },
];

export const MOCK_NUTRITION: FreeNutrition[] = [
  {
    _id: 'nut_01',
    title: 'High-Protein Muscle Builder Protocol',
    content: 'Targeted macro plan structured around 200g clean protein, complex slow-digesting carbs, and essential omega fatty acids.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=600',
    tags: ['Muscle Gain', 'High Protein', 'Lean Bulk'],
    calories: 2850,
    protein: 210,
    carbs: 320,
    fats: 75,
    meals: [
      {
        name: 'Power Oats & Whey Supreme',
        mealType: 'Breakfast',
        calories: 680,
        protein: 48,
        carbs: 82,
        fats: 16,
        imageUrl: 'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&q=80&w=400',
        ingredients: ['100g Rolled Oats', '1 Scoop Isolate Whey', '1 Banana', '25g Almond Butter', 'Cinnamon & Chia Seeds'],
      },
      {
        name: 'Flame-Grilled Salmon & Jasmine Rice',
        mealType: 'Lunch',
        calories: 820,
        protein: 56,
        carbs: 88,
        fats: 24,
        imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&q=80&w=400',
        ingredients: ['200g Wild Atlantic Salmon', '200g Steamed Jasmine Rice', '150g Grilled Asparagus', 'Lemon Olive Oil Drizzle'],
      },
      {
        name: 'Herb-Roasted Chicken & Sweet Potato',
        mealType: 'Dinner',
        calories: 850,
        protein: 64,
        carbs: 95,
        fats: 20,
        imageUrl: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&q=80&w=400',
        ingredients: ['220g Free-Range Chicken Breast', '250g Baked Sweet Potato', 'Steamed Broccoli with Garlic', 'Avocado Oil'],
      },
      {
        name: 'Greek Yogurt & Berry Crunch',
        mealType: 'Snack',
        calories: 500,
        protein: 42,
        carbs: 55,
        fats: 15,
        imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=400',
        ingredients: ['250g 0% Greek Yogurt', 'Fresh Blueberries & Raspberries', '30g Walnuts', 'Drizzle Raw Honey'],
      },
    ],
  },
  {
    _id: 'nut_02',
    title: 'Lean Shred & Ketogenic Ignition',
    content: 'Low-carb ketogenic protocol optimized for accelerated fat oxidation while preserving metabolically active muscle tissue.',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=600',
    tags: ['Keto', 'Fat Loss', 'Low Carb'],
    calories: 2100,
    protein: 175,
    carbs: 30,
    fats: 140,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    _id: 'prod_01',
    name: 'SmartCoach ISO-Pure Whey Isolate',
    description: '100% Cross-flow microfiltered cold-processed whey isolate. 27g protein per scoop with zero added sugars.',
    price: 64.99,
    salePrice: 54.99,
    category: 'supplements',
    stock: 85,
    isActive: true,
    averageRating: 4.9,
    reviewCount: 142,
    images: ['https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?auto=format&fit=crop&q=80&w=500'],
    flavors: ['Double Rich Chocolate', 'Madagascar Vanilla', 'Salted Caramel Crunch'],
    specifications: { Servings: '30', Protein: '27g', BCAAs: '6.2g' },
  },
  {
    _id: 'prod_02',
    name: 'NeuroDrive Pre-Workout Igniter',
    description: 'Clinical dose citrulline, beta-alanine, and alpha-GPC for laser tunnel focus, vascularity, and boundless power.',
    price: 49.99,
    category: 'supplements',
    stock: 120,
    isActive: true,
    averageRating: 4.8,
    reviewCount: 98,
    images: ['https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&q=80&w=500'],
    flavors: ['Electric Lime Rush', 'Blue Raspberry Blast', 'Watermelon Surge'],
    specifications: { Servings: '40', Caffeine: '300mg', Citrulline: '8000mg' },
  },
  {
    _id: 'prod_03',
    name: 'Heavy Duty 10mm Lever Lifting Belt',
    description: 'Competition grade top-grain leather with hardened alloy matte black quick-release lever mechanism.',
    price: 119.99,
    salePrice: 99.99,
    category: 'equipment',
    stock: 42,
    isActive: true,
    averageRating: 5.0,
    reviewCount: 76,
    images: ['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=500'],
    sizes: ['Small (28-32")', 'Medium (32-36")', 'Large (36-40")', 'XL (40-44")'],
    specifications: { Thickness: '10mm', Material: 'Vegetable-tanned Leather' },
  },
  {
    _id: 'prod_04',
    name: 'Seamless Compression Tech Tee',
    description: 'Ultra-breathable 4-way stretch fabric engineered to keep you cool, dry, and mobile during heavy reps.',
    price: 38.00,
    category: 'apparel',
    stock: 64,
    isActive: true,
    averageRating: 4.7,
    reviewCount: 51,
    images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=500'],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    specifications: { Fit: 'Athletic Tapered', Fabric: 'Polyester / Elastane' },
  },
  {
    _id: 'prod_05',
    name: 'SmartCoach Insulated Steel Shaker (800ml)',
    description: 'Double-wall vacuum insulated stainless steel shaker with built-in silent agitator and leak-proof spout.',
    price: 28.00,
    salePrice: 22.50,
    category: 'accessories',
    stock: 150,
    isActive: true,
    averageRating: 4.9,
    reviewCount: 88,
    images: ['https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=500'],
    specifications: { Capacity: '800ml', Material: '18/8 Food Grade Steel' },
  },
  {
    _id: 'prod_06',
    name: 'Heavy Resistance Band Set (5-Pack)',
    description: '100% natural Malaysian latex loop bands ranging from 15 lbs to 150 lbs of tension for warming up and resistance work.',
    price: 34.99,
    category: 'equipment',
    stock: 90,
    isActive: true,
    averageRating: 4.8,
    reviewCount: 64,
    images: ['https://images.unsplash.com/photo-1598289431512-b97b0917affc?auto=format&fit=crop&q=80&w=500'],
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    _id: 'conv_01',
    participant: {
      _id: 'user_coach_01',
      name: 'Coach Elena Rostova',
      role: 'Head Strength Coach',
      avatarUrl: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?auto=format&fit=crop&q=80&w=200',
      isOnline: true,
    },
    lastMessage: {
      _id: 'msg_01',
      conversationId: 'conv_01',
      senderId: 'user_coach_01',
      senderName: 'Coach Elena',
      content: 'Your bench press form looks much tighter! Make sure you keep that upper back pinched into the pad.',
      createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
      isRead: false,
    },
    unreadCount: 1,
    updatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    _id: 'conv_02',
    participant: {
      _id: 'user_coach_02',
      name: 'Coach David Kovac',
      role: 'Mobility & Rehab Specialist',
      avatarUrl: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?auto=format&fit=crop&q=80&w=200',
      isOnline: false,
    },
    lastMessage: {
      _id: 'msg_02',
      conversationId: 'conv_02',
      senderId: 'user_athlete_01',
      senderName: 'Marcus',
      content: 'Added the hip 90/90 mobility routine before squats today, hips felt completely unlocked.',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      isRead: true,
    },
    unreadCount: 0,
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
];

export const MOCK_MESSAGES: Record<string, Message[]> = {
  conv_01: [
    {
      _id: 'm1',
      conversationId: 'conv_01',
      senderId: 'user_coach_01',
      senderName: 'Coach Elena',
      content: 'Hey Marcus! Welcome to the upper body block. Have you had a chance to review the RPE targets?',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    },
    {
      _id: 'm2',
      conversationId: 'conv_01',
      senderId: 'user_athlete_01',
      senderName: 'Marcus',
      content: 'Yes! Planning to keep incline dumbbell bench right around RPE 8 today with 32kg dumbbells.',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    },
    {
      _id: 'm3',
      conversationId: 'conv_01',
      senderId: 'user_coach_01',
      senderName: 'Coach Elena',
      content: 'Your bench press form looks much tighter! Make sure you keep that upper back pinched into the pad.',
      createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    },
  ],
};

export const MOCK_WEIGHT_LOGS: WeightLogEntry[] = [
  { id: '1', date: '2026-08-01', weight: 77.2, bodyFat: 15.2 },
  { id: '2', date: '2026-08-08', weight: 77.8, bodyFat: 15.0 },
  { id: '3', date: '2026-08-15', weight: 78.1, bodyFat: 14.8 },
  { id: '4', date: '2026-08-22', weight: 78.6, bodyFat: 14.6 },
  { id: '5', date: '2026-08-29', weight: 78.9, bodyFat: 14.5 },
  { id: '6', date: '2026-09-05', weight: 79.2, bodyFat: 14.3 },
  { id: '7', date: '2026-09-12', weight: 79.5, bodyFat: 14.1 },
];

export const MOCK_VOLUME_LOGS: WorkoutVolumeEntry[] = [
  { date: 'Mon', volume: 12400, workoutsCount: 1, caloriesBurned: 520 },
  { date: 'Tue', volume: 14200, workoutsCount: 1, caloriesBurned: 580 },
  { date: 'Wed', volume: 0, workoutsCount: 0, caloriesBurned: 180 },
  { date: 'Thu', volume: 13800, workoutsCount: 1, caloriesBurned: 510 },
  { date: 'Fri', volume: 15600, workoutsCount: 1, caloriesBurned: 620 },
  { date: 'Sat', volume: 8400, workoutsCount: 1, caloriesBurned: 390 },
  { date: 'Sun', volume: 0, workoutsCount: 0, caloriesBurned: 150 },
];

export const MOCK_PHOTO_LOGS: ProgressPhotoEntry[] = [
  {
    id: 'p1',
    date: '2026-08-01',
    imageUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&q=80&w=400',
    tag: 'Front',
    weight: 77.2,
    notes: 'Starting baseline condition for clean hypertrophy phase',
  },
  {
    id: 'p2',
    date: '2026-09-12',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=400',
    tag: 'Front',
    weight: 79.5,
    notes: 'Noticeable delt and upper chest fullness, waist maintained at 31 inches',
  },
];
